# SwiftLint configuration for CLARITY Pulse

# Rule configuration
disabled_rules:
  - line_length # Often too restrictive for modern SwiftUI code
  - trailing_whitespace
  - vertical_whitespace
  - nesting # Can sometimes conflict with SwiftUI view structure
  - identifier_name # Can be too strict with acronyms or short names

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - function_default_parameter_at_end
  - nimble_operator
  - redundant_nil_coalescing
  - sorted_imports
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - let_var_whitespace
  - private_outlet
  - unowned_variable_capture
  - weak_delegate

# Paths to include for linting
included:
  - clarity-loop-frontend

# Paths to ignore for linting
excluded:
  - Pods
  - vendor
  - Carthage
  - clarity-loop-frontend/clarity-loop-frontend.xcodeproj

# Rule-specific configurations
cyclomatic_complexity:
  warning: 15
  error: 25

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1200

large_tuple:
  warning: 3
  error: 4

force_cast: warning
force_try: warning
force_unwrapping: error

colon:
  flexible_right_spacing: true

trailing_comma:
  mandatory_comma: true

reporter: "xcode" # Integrates directly with Xcode 